<?php return array (
  0 => 'Reply',
  1 => 'Replies',
  2 => 'Status Archive',
  3 => ':display_name\'s Status Updates',
  4 => 'All users',
  5 => 'User has no status updates',
  6 => 'No status messages logged',
  7 => 'Browse Archive',
  8 => 'Track Using RSS',
  9 => 'Recent Messages',
  10 => 'Status Update',
  11 => 'Status Module',
  12 => 'Can post updates?',
  13 => 'Failed to post reply to selected status message',
  14 => 'Reply has been successfully posted',
  15 => 'Selected status update has been successfully deleted',
  16 => 'Failed to delete selected status update',
  17 => 'Status Update #:id',
  18 => 'Status Updates',
  19 => 'Status message is required',
  20 => 'Adds simple, globally available communication channel. Tell your team members or clients what you are working on or have a quick chat',
  21 => 'Module will be deactivated. All data generated using it will be deleted',
); ?>