<?php $clickheatConf = array (
  'logPath' => '/var/www/vhosts/ar/content/clickheat/logs/',
  'cachePath' => '/var/www/vhosts/ar/content/clickheat/cache/',
  'referers' => 
  array (
    0 => 'ar.hollisint.com',
    1 => 'ar.scotton.hollisint.com',
    2 => 'ar.theinstrom.hollisint.com',
  ),
  'groups' => false,
  'filesize' => 0,
  'adminLogin' => 'ar_admin',
  'adminPass' => '6e5b407b24584908cf7899a09777fdd5',
  'viewerLogin' => '',
  'viewerPass' => '',
  'memory' => 128,
  'step' => 5,
  'dot' => 19,
  'flush' => 40,
  'start' => 'm',
  'palette' => false,
  'heatmap' => true,
  'hideIframes' => true,
  'hideFlashes' => true,
  'yesterday' => false,
  'alpha' => 80,
  '__screenSizes' => 
  array (
    0 => 0,
    1 => 240,
    2 => 640,
    3 => 800,
    4 => 1024,
    5 => 1152,
    6 => 1280,
    7 => 1440,
    8 => 1600,
    9 => 1800,
  ),
  '__browsersList' => 
  array (
    'all' => '',
    'msie' => 'Internet Explorer',
    'firefox' => 'Firefox',
    'chrome' => 'Chrome',
    'safari' => 'Safari',
    'opera' => 'Opera',
    'unknown' => '',
  ),
  'version' => '1.12',
); ?>