<?php return array (
  0 => 'No one is responsible',
  1 => 'All of :company_name',
  2 => 'Due on',
  3 => 'Filter Group',
  4 => 'This filter can be used only by me',
  5 => 'Order by',
  6 => 'Objects per Page',
  7 => 'Select Yes to create a private filter. This filter will not be visible to other users and you will be the only person who can use it.',
  8 => 'Show Assignments...',
  9 => 'Assigned to',
  10 => 'Anyone',
  11 => 'Not Assigned',
  12 => 'Person Accessing the Page is Assigned or Responsible',
  13 => 'Person Accessing the Page is Responsible Only',
  14 => 'Member of a Company',
  15 => 'Selected Users',
  16 => 'Any Time',
  17 => 'Late',
  18 => 'Tomorrow',
  19 => 'This Week',
  20 => 'Next Week',
  21 => 'This Month',
  22 => 'Next Month',
  23 => 'Specific Date',
  24 => 'Specific Range',
  25 => 'In Project',
  26 => 'Selected Projects ...',
  27 => 'Active Only',
  28 => 'Completed Only',
  29 => 'Both Active and Completed',
  30 => 'Display and Order',
  31 => 'Priority, Highest First',
  32 => 'Priority, Lowest First',
  33 => 'Due Date, Late First',
  34 => 'Due Date, Late at the End',
  35 => 'Creation Time, Older First',
  36 => 'Creation Time, Newer First',
  37 => 'New Filter',
  38 => 'Edit Filter',
  39 => 'Filter',
  40 => 'Toggle Filter Details',
  41 => 'Update Filter',
  42 => 'This filter displays',
  43 => 'Tasks assigned to anyone',
  44 => 'Tasks not assigned to anyone',
  45 => 'Tasks assigned to person using this filter',
  46 => 'Tasks person using this filter is responsible for',
  47 => 'Tasks assigned to members of :company company',
  48 => 'Tasks assigned to :to',
  49 => 'Tasks that are late',
  50 => 'Tasks that are due today',
  51 => 'Tasks that are due tomorrow',
  52 => 'Tasks that are due this week',
  53 => 'Tasks that are due next week',
  54 => 'Tasks that are due this month',
  55 => 'Tasks that are due next month',
  56 => 'Tasks that are due on :from',
  57 => 'Tasks that are due between :from and :to',
  58 => 'Tasks from all active projects',
  59 => 'Tasks from :project project(s)',
  60 => 'Only active tasks',
  61 => 'Only completed tasks',
  62 => 'Both active and completed tasks',
  63 => 'Tasks are ordered by :by and system shows :count tasks per page',
  64 => 'Tasks are ordered by :by',
  65 => 'There are no tasks that match selected filter rules',
  66 => 'Track using RSS',
  67 => 'Are you sure that you want to delete this filter?',
  68 => 'Delete Filter',
  69 => 'Filename',
  70 => 'Attach a File',
  71 => 'Show Details',
  72 => 'Attach Another File',
  73 => 'There are no files attached to this object',
  74 => 'Size and Type',
  75 => 'Update attachment',
  76 => 'New Category',
  77 => 'Edit category',
  78 => 'Categories',
  79 => 'There are no categories in this section!',
  80 => 'There are no object on this page. Go back to <a href=":categories_url">categories page</a>.',
  81 => 'Your Comment',
  82 => 'Comments',
  83 => 'said',
  84 => 'Complete :object_type with this comment',
  85 => 'Attach Files',
  86 => 'This :type is locked for new comments',
  87 => 'Permalink',
  88 => 'Update Comment',
  89 => 'New Comment',
  90 => 'You are about to post a comment to "<a href=":url">:name</a>" :type',
  91 => 'Edit Comment',
  92 => 'Subscribers',
  93 => 'Everyone involved in a discussion',
  94 => 'Selected User',
  95 => 'Optional Comment',
  96 => 'There are no assignees',
  97 => 'There are no users subscribed to this object',
  98 => 'No users involved in a discussion',
  99 => 'Active Reminders',
  100 => 'Reminder',
  101 => 'Sent',
  102 => 'by <a href=":user_url">:user_name</a>',
  103 => 'There are no reminders for you',
  104 => 'is subscribed to this :type',
  105 => 'are subscribed to this :type',
  106 => 'There are no users subscribed to this :type',
  107 => 'person',
  108 => 'people',
  109 => ':subscribers_count :person subscribed to this :type',
  110 => 'Manage / Add',
  111 => 'Tags',
  112 => 'There are no tagged objects in this project',
  113 => 'All tags',
  114 => 'Tag: :tag',
  115 => 'There are no objects tagged with :tag',
  116 => 'Tasks',
  117 => 'There are no active Tasks in this :object_type',
  118 => 'Set priority and due date...',
  119 => 'Done adding tasks?',
  120 => 'Add Another Task',
  121 => 'Show :remaining_count remaining completed tasks',
  122 => 'You are about to create a new task on "<a href=":view_url"><strong>:name</strong></a>" :type',
  123 => 'Add task',
  124 => 'Edit task',
  125 => 'Back to <a href=":view_url">:name</a>',
  126 => 'Failed to delete \':name\' filter',
  127 => 'Filter \':name\' has been created',
  128 => 'Filter \':name\' has been updated',
  129 => 'Filter \':name\' has been deleted',
  130 => 'Assignments',
  131 => 'Failed to update :filename',
  132 => 'File :filename has been updated',
  133 => 'Parent object not found',
  134 => 'Comment successfully posted',
  135 => 'Comment has been updated',
  136 => 'Failed to dismiss selected reminder',
  137 => '0 users reminded',
  138 => 'Selected reminder has been dismissed',
  139 => 'Users reminded: :users',
  140 => 'Failed to complete task ":name"',
  141 => 'Failed to open task ":name"',
  142 => 'Task ":name" has been added',
  143 => 'Task ":name" has been updated',
  144 => 'Task ":name" has been completed',
  145 => 'Task ":name" has been opened',
  146 => '<strong>:count</strong>&nbsp;reminders',
  147 => '<strong>:count</strong>&nbsp;reminder',
  148 => 'Anyone can pick and complete this task',
  149 => ':name is no longer responsible for this task',
  150 => ':name has been removed from this task',
  151 => ':name is responsible for this task',
  152 => ':name has been added to this task',
  153 => 'Max size of file that you can upload is :size',
  154 => 'Max total size of files you can upload is :size',
  155 => 'Unknown Category',
  156 => 'is responsible',
  157 => 'Other assignees',
  158 => 'Click to unsubscribe',
  159 => 'Click to subscribe',
  160 => '-- No tags --',
  161 => 'No time tracked',
  162 => ':total hours logged',
  163 => ':total hours logged - :object_time for the ticket and :tasks_time for tasks',
  164 => 'Time',
  165 => 'Please insert new category name',
  166 => 'New Category...',
  167 => '-- System Default (:filter) --',
  168 => '<a href=":user_url">:user_name</a> commented <a href=":parent_url">:parent_name</a> :parent_type',
  169 => '<a href=":user_url">:user_name</a> commented <a href=":parent_url">:parent_name</a> :parent_type in <a href=":project_view_url">:project_name</a> project',
  170 => '<a href=":user_url">:user_name</a> posted a new comment:',
  171 => 'View Comment',
  172 => 'All Comments (:count)',
  173 => ':user_name commented <a href=":parent_url">:parent_name</a> :parent_type',
  174 => ':user_name posted a new comment:',
  175 => '<a href=":user_url">:user_name</a> added a new task <a href=":url">:name</a> to <a href=":parent_url">:parent_name</a> :parent_type',
  176 => '<a href=":user_url">:user_name</a> created a new task: <a href=":url">:name</a> in <a href=":project_view_url">:project_name</a> project',
  177 => ':user_name created a new task: <a href=":object_url">:object_name</a>',
  178 => '<a href=":user_url">:user_name</a> completed <del><a href=":url">:name</a></del> :type',
  179 => '<a href=":user_url">:user_name</a> completed <del><a href=":url">:name</a></del> :type in <a href=":project_view_url">:project_name</a> project',
  180 => ':user_name completed <del><a href=":object_url">:object_name</a></del> :object_type',
  181 => 'Opened',
  182 => '<a href=":user_url">:user_name</a> reopened <a href=":url">:name</a> :type',
  183 => '<a href=":user_url">:user_name</a> reopened <a href=":url">:name</a> :type in <a href=":project_view_url">:project_name</a> project',
  184 => ':user_name reopened <a href=":object_url">:object_name</a> :object_type',
  185 => 'Due date, Late First',
  186 => 'Due date, Late at the End',
  187 => 'Creation Time, Newest First',
  188 => 'Creation Time, Oldest First',
  189 => 'Filter name needs to be unique',
  190 => 'Field name is required',
  191 => 'Default filter can\'t be marked as private',
  192 => 'Filter already used as default by other users can\'t be marked as private',
  193 => 'Other',
  194 => 'File name is required. Min length is 3 letters',
  195 => 'Category :category_name already exists',
  196 => 'Category name is required. Min length is 3 letters',
  197 => 'Controller name is required. Min length is 3 letters',
  198 => 'Comment on :name',
  199 => 'User needs to be selected',
  200 => 'Object needs to be selected',
  201 => 'Task text is required. Min length is 3 letters',
  202 => 'Resources',
  203 => 'System level resources support - comments, categories, tags...',
); ?>