<?php /* Smarty version 2.6.16, created on 2012-07-27 13:11:56
         compiled from /mnt/raid0/vhosts/accident-review/content-backend/activecollab/application/modules/system/views/auth/login.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('block', 'title', '/mnt/raid0/vhosts/accident-review/content-backend/activecollab/application/modules/system/views/auth/login.tpl', 1, false),array('block', 'form', '/mnt/raid0/vhosts/accident-review/content-backend/activecollab/application/modules/system/views/auth/login.tpl', 9, false),array('block', 'wrap', '/mnt/raid0/vhosts/accident-review/content-backend/activecollab/application/modules/system/views/auth/login.tpl', 10, false),array('block', 'label', '/mnt/raid0/vhosts/accident-review/content-backend/activecollab/application/modules/system/views/auth/login.tpl', 12, false),array('block', 'lang', '/mnt/raid0/vhosts/accident-review/content-backend/activecollab/application/modules/system/views/auth/login.tpl', 22, false),array('block', 'wrap_buttons', '/mnt/raid0/vhosts/accident-review/content-backend/activecollab/application/modules/system/views/auth/login.tpl', 26, false),array('block', 'link', '/mnt/raid0/vhosts/accident-review/content-backend/activecollab/application/modules/system/views/auth/login.tpl', 27, false),array('block', 'submit', '/mnt/raid0/vhosts/accident-review/content-backend/activecollab/application/modules/system/views/auth/login.tpl', 28, false),array('function', 'brand', '/mnt/raid0/vhosts/accident-review/content-backend/activecollab/application/modules/system/views/auth/login.tpl', 3, false),array('function', 'text_field', '/mnt/raid0/vhosts/accident-review/content-backend/activecollab/application/modules/system/views/auth/login.tpl', 13, false),array('function', 'password_field', '/mnt/raid0/vhosts/accident-review/content-backend/activecollab/application/modules/system/views/auth/login.tpl', 18, false),array('function', 'checkbox_field', '/mnt/raid0/vhosts/accident-review/content-backend/activecollab/application/modules/system/views/auth/login.tpl', 22, false),array('modifier', 'clean', '/mnt/raid0/vhosts/accident-review/content-backend/activecollab/application/modules/system/views/auth/login.tpl', 3, false),)), $this); ?>
<?php $this->_tag_stack[] = array('title', array()); $_block_repeat=true;smarty_block_title($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Login<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_title($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>
<div id="login_company_logo">
  <img src="<?php echo smarty_function_brand(array('what' => 'logo'), $this);?>
" alt="<?php echo ((is_array($_tmp=$this->_tpl_vars['owner_company']->getName())) ? $this->_run_mod_handler('clean', true, $_tmp) : smarty_modifier_clean($_tmp)); ?>
 logo" />
</div>

<div id="auth_dialog_container">
  <div id="auth_dialog_container_inner">
    <div id="auth_dialog">
    <?php $this->_tag_stack[] = array('form', array('method' => 'post','autofocus' => $this->_tpl_vars['auto_focus'],'show_errors' => false)); $_block_repeat=true;smarty_block_form($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>
      <?php $this->_tag_stack[] = array('wrap', array('field' => 'login','class' => 'auth_elements')); $_block_repeat=true;smarty_block_wrap($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>
        <?php $this->_tag_stack[] = array('wrap', array('field' => 'email')); $_block_repeat=true;smarty_block_wrap($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>
          <?php $this->_tag_stack[] = array('label', array('for' => 'loginFormEmail')); $_block_repeat=true;smarty_block_label($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Email Address<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_label($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>
          <?php echo smarty_function_text_field(array('name' => 'login[email]','value' => $this->_tpl_vars['login_data']['email'],'id' => 'loginFormEmail','tabindex' => 1), $this);?>

        <?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_wrap($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>
        
        <?php $this->_tag_stack[] = array('wrap', array('field' => 'password')); $_block_repeat=true;smarty_block_wrap($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>
          <?php $this->_tag_stack[] = array('label', array('for' => 'loginFormPassword')); $_block_repeat=true;smarty_block_label($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Password<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_label($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>
          <?php echo smarty_function_password_field(array('name' => 'login[password]','value' => $this->_tpl_vars['login_data']['password'],'id' => 'loginFormPassword','tabindex' => 2), $this);?>

        <?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_wrap($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>
        
        <?php $this->_tag_stack[] = array('wrap', array('field' => 'remember_me')); $_block_repeat=true;smarty_block_wrap($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>
          <label for="loginFormRemember"><?php echo smarty_function_checkbox_field(array('name' => "login[remember]",'checked' => $this->_tpl_vars['login_data']['remember'],'class' => 'inlineInput','id' => 'loginFormRemember','tabindex' => 3), $this);?>
 <?php $this->_tag_stack[] = array('lang', array()); $_block_repeat=true;smarty_block_lang($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Remember me for 14 days<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lang($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></label>
        <?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_wrap($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>
      <?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_wrap($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>
      
      <?php $this->_tag_stack[] = array('wrap_buttons', array()); $_block_repeat=true;smarty_block_wrap_buttons($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>
        <?php $this->_tag_stack[] = array('link', array('href' => "?route=forgot_password",'class' => 'forgot_password_link')); $_block_repeat=true;smarty_block_link($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Forgot password?<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_link($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>
        <?php $this->_tag_stack[] = array('submit', array('tabindex' => 4)); $_block_repeat=true;smarty_block_submit($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Login<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_submit($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>
      <?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_wrap_buttons($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>
      <div class="clear"></div>
    <?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_form($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>
    </div>
  </div>
</div>