<?php /* Smarty version 2.6.16, created on 2012-07-27 13:12:10
         compiled from /mnt/raid0/vhosts/accident-review/content-backend/activecollab/application/modules/reporting/views/Reports/tabs.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'assemble', '/mnt/raid0/vhosts/accident-review/content-backend/activecollab/application/modules/reporting/views/Reports/tabs.tpl', 2, false),array('block', 'lang', '/mnt/raid0/vhosts/accident-review/content-backend/activecollab/application/modules/reporting/views/Reports/tabs.tpl', 2, false),)), $this); ?>
<ul class="category_list">
<li <?php if ($this->_tpl_vars['request']->getController() == 'reports' && $this->_tpl_vars['request']->getAction() == 'report_most_active_customers'): ?>class="selected"<?php endif; ?>><a href="<?php echo smarty_function_assemble(array('route' => 'report_most_active_customers'), $this);?>
"><span><?php $this->_tag_stack[] = array('lang', array()); $_block_repeat=true;smarty_block_lang($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Most Active Customers<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lang($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></span></a></li>
<li <?php if ($this->_tpl_vars['request']->getController() == 'reports' && $this->_tpl_vars['request']->getAction() == 'report_most_revenue'): ?>class="selected"<?php endif; ?>><a href="<?php echo smarty_function_assemble(array('route' => 'report_most_revenue'), $this);?>
"><span><?php $this->_tag_stack[] = array('lang', array()); $_block_repeat=true;smarty_block_lang($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Most Revenue<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lang($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></span></a></li>
<li <?php if ($this->_tpl_vars['request']->getController() == 'reports' && $this->_tpl_vars['request']->getAction() == 'report_cases_by_month_week'): ?>class="selected"<?php endif; ?>><a href="<?php echo smarty_function_assemble(array('route' => 'report_cases_by_month_week'), $this);?>
"><span><?php $this->_tag_stack[] = array('lang', array()); $_block_repeat=true;smarty_block_lang($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Cases By Month/Week<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lang($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></span></a></li>
  <li <?php if ($this->_tpl_vars['request']->getController() == 'reports' && $this->_tpl_vars['request']->getAction() == 'index'): ?>class="selected"<?php endif; ?>><a href="<?php echo smarty_function_assemble(array('route' => 'reports'), $this);?>
"><span><?php $this->_tag_stack[] = array('lang', array()); $_block_repeat=true;smarty_block_lang($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Cases By Investigator<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lang($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></span></a></li>
  <li <?php if ($this->_tpl_vars['request']->getController() == 'reports' && $this->_tpl_vars['request']->getAction() == 'report_time_by_investigator'): ?>class="selected"<?php endif; ?>><a href="<?php echo smarty_function_assemble(array('route' => 'report_time_by_investigator'), $this);?>
"><span><?php $this->_tag_stack[] = array('lang', array()); $_block_repeat=true;smarty_block_lang($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Time By Investigator<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lang($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></span></a></li>
  <li <?php if ($this->_tpl_vars['request']->getController() == 'reports' && $this->_tpl_vars['request']->getAction() == 'report_average_case_time'): ?>class="selected"<?php endif; ?>><a href="<?php echo smarty_function_assemble(array('route' => 'report_average_case_time'), $this);?>
"><span><?php $this->_tag_stack[] = array('lang', array()); $_block_repeat=true;smarty_block_lang($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Average Case Time<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lang($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></span></a></li>
  <li <?php if ($this->_tpl_vars['request']->getController() == 'reports' && $this->_tpl_vars['request']->getAction() == 'report_revenue_calculator'): ?>class="selected"<?php endif; ?>><a href="<?php echo smarty_function_assemble(array('route' => 'report_revenue_calculator'), $this);?>
"><span><?php $this->_tag_stack[] = array('lang', array()); $_block_repeat=true;smarty_block_lang($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Revenue Calculator<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lang($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></span></a></li>
</ul>
<div class="clear"></div>