<?php /* Smarty version 2.6.16, created on 2012-07-31 18:53:56
         compiled from /var/www/vhosts/accidentreview.com/content-backend/activecollab/application/modules/invoicing/views/invoices/tabs.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'assemble', '/var/www/vhosts/accidentreview.com/content-backend/activecollab/application/modules/invoicing/views/invoices/tabs.tpl', 2, false),array('block', 'lang', '/var/www/vhosts/accidentreview.com/content-backend/activecollab/application/modules/invoicing/views/invoices/tabs.tpl', 2, false),)), $this); ?>
<ul class="category_list">
  <li <?php if ($this->_tpl_vars['request']->getController() == 'invoices' && $this->_tpl_vars['request']->getAction() == 'index'): ?>class="selected"<?php endif; ?>><a href="<?php echo smarty_function_assemble(array('route' => 'invoices'), $this);?>
"><span><?php $this->_tag_stack[] = array('lang', array()); $_block_repeat=true;smarty_block_lang($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Invoices<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lang($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></span></a></li>
  <li <?php if ($this->_tpl_vars['request']->getController() == 'invoice_payments'): ?>class="selected"<?php endif; ?>><a href="<?php echo smarty_function_assemble(array('route' => 'invoice_payments'), $this);?>
"><span><?php $this->_tag_stack[] = array('lang', array()); $_block_repeat=true;smarty_block_lang($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Payments<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lang($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></span></a></li>
  <li <?php if (( $this->_tpl_vars['request']->getController() == 'invoices' && $this->_tpl_vars['request']->getAction() == 'archive' ) || ( $this->_tpl_vars['request']->getController() == 'invoices_archive' )): ?>class="selected"<?php endif; ?>><a href="<?php echo smarty_function_assemble(array('route' => 'invoices_archive'), $this);?>
"><span><?php $this->_tag_stack[] = array('lang', array()); $_block_repeat=true;smarty_block_lang($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Archive<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lang($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></span></a></li>
</ul>
<div class="clear"></div>