<?php return array (
  0 => 'Show all paths',
  1 => 'Are you sure that you wish to delete this repository from activeCollab?',
  2 => 'Hide all paths',
  3 => 'Repository update',
  4 => 'Checking for updates...',
  5 => 'Sending subscriptions...',
  6 => 'Done!',
  7 => 'Importing commits</p>',
  8 => 'Repository successfully updated',
  9 => 'Repository is already up-to-date',
  10 => 'Error getting new commits',
  11 => 'Item info',
  12 => 'Fetching data...',
  13 => 'Are you sure that you wish to delete remove this mapping?',
  14 => 'Please select activeCollab user',
  15 => 'Subversion executable found',
  16 => 'Error accessing SVN executable',
  17 => 'Enter revision number',
  18 => 'Please insert a revision number',
  19 => 'Enter new revision number',
  20 => 'Checking...',
  21 => 'You need to enter repository URL first',
  22 => 'Connection parameters are valid',
  23 => 'Could not connect to repository:',
); ?>