<?php return array (
  'About Milestones' => 'About Milestones',
  'Milestones Mark Key Points in a Project' => 'Milestones Mark Key Points in a Project',
  'Milestones mark key points in a project so you can have a bird-eye view over things that needs to be done, when and who is responsible. Milestone can be a single day event or a time period with start and due date. When you need more details, you can click on a milestone\'s name to "zoom in" and see all related discussions, files and tasks' => 'Milestones mark key points in a project so you can have a bird-eye view over things that needs to be done, when and who is responsible. Milestone can be a single day event or a time period with start and due date. When you need more details, you can click on a milestone\'s name to "zoom in" and see all related discussions, files and tasks',
  'Keep Your Calendar Application in Sync with Milestones' => 'Keep Your Calendar Application in Sync with Milestones',
  'If you want to have milestones synchronized with calendars in your favorite calendar application (iCal, Outlook 2007, Google Calendar), then subscribe to iCalendar feed provided by the system. On the Calendar page you can find global feed with milestones and tasks from all active projects. The system also provides a feed for each project and you can find it by visiting overview page of the particular project' => 'If you want to have milestones synchronized with calendars in your favorite calendar application (iCal, Outlook 2007, Google Calendar), then subscribe to iCalendar feed provided by the system. On the Calendar page you can find global feed with milestones and tasks from all active clients. The system also provides a feed for each client and you can find it by visiting overview page of the particular client',
  'Email Notifications' => 'Email Notifications',
  'Subscribe to a milestone to receive email notification when it is completed or reopened. The person responsible for the milestone can edit the list of subscribers using Manage Subscriptions tool (available from Options menu)' => 'Subscribe to a milestone to receive email notification when it is completed or reopened. The person responsible for the milestone can edit the list of subscribers using Manage Subscriptions tool (available from Options menu)',
  'Start on' => 'Start on',
  'Notes' => 'Notes',
  'New Milestone' => 'New Milestone',
  'Completed Milestones' => 'Completed Milestones',
  'There are no completed milestones in this project. <a href=":add_url">Create a milestone</a>.' => 'There are no completed milestones in this client. <a href=":add_url">Create a milestone</a>.',
  'Edit Milestone' => 'Edit Milestone',
  'Milestones' => 'Milestones',
  'Milestone' => 'Milestone',
  'Active milestones' => 'Active milestones',
  'iCalendar' => 'iCalendar',
  'No active milestones here' => 'No active milestones here',
  'Would you like to <a href=":add_url">create one</a>' => 'Would you like to <a href=":add_url">create one</a>',
  'Milestone <a href=":url">:name</a> has been created' => 'Milestone <a href=":url">:name</a> has been created',
  'Back' => 'Back',
  'Reschedule milestone' => 'Reschedule milestone',
  'With Successive Milestones' => 'With Successive Milestones',
  'Also reschedule all tickets and tasks that belong to milestones you are rescheduling' => 'Also reschedule all jobs and tasks that belong to milestones you are rescheduling',
  'Reschedule' => 'Reschedule',
  'From / To' => 'From / To',
  'Add to Milestone' => 'Add to Milestone',
  'No notes...' => 'No notes...',
  'No tasks in this milestone...' => 'No tasks in this milestone...',
  'Milestone ":name" has been created' => 'Milestone ":name" has been created',
  'Milestone ":name" has been updated' => 'Milestone ":name" has been updated',
  'or' => 'or',
  '<a href=":url">Click here</a> if you wish to reschedule this milestone' => '<a href=":url">Click here</a> if you wish to reschedule this milestone',
  'You don\'t have permission for this action' => 'You don\'t have permission for this action',
  'Exporting milestones data...' => 'Exporting milestones data...',
  'Unknown Milestone' => 'Unknown Milestone',
  'This milestone does not have any successive milestones' => 'This milestone does not have any successive milestones',
  'Adjust all successive milestone by the same number of days' => 'Adjust all successive milestone by the same number of days',
  'Adjust only selected successive milestones by the same number of days' => 'Adjust only selected successive milestones by the same number of days',
  'Don\'t change anything' => 'Don\'t change anything',
  'Add milestones to projects' => 'Add milestones to projects',
  'Start date is not valid' => 'Start date is not valid',
  'Due date is not valid' => 'Due date is not valid',
  'Milestone name is required' => 'Milestone name is required',
  'Start date is required' => 'Start date is required',
  'Due date is required' => 'Due date is required',
  'Start date needs to be before due date' => 'Start date needs to be before due date',
) ?>