<?php return array (
  'About Files' => 'About Files',
  'Upload Files, File Revisions and Collaborate' => 'Upload Files, File Revisions and Collaborate',
  'Use Files section to upload files, discuss them, upload and compare versions and more. You can upload and track versions of any file. Files attached to objects in other sections of project are also listed here' => 'Use Files section to upload files, discuss them, upload and compare versions and more. You can upload and track versions of any file. Files attached to objects in other sections of client are also listed here',
  'Organize in Categories and Associate with Milestones' => 'Organize in Categories and Associate with Milestones',
  'Files can be sorted in categories and associated with milestones; both relations are optional. Filter files by category using the tabs on the right' => 'Files can be sorted in categories and associated with milestones; both relations are optional. Filter files by category using the tabs on the right',
  'Have a Discussion with your Team or Clients' => 'Have a Discussion with your Team or Clients',
  'Post an unlimited number of comments. Use them to discuss file and file revisions with your colleagues and clients' => 'Post an unlimited number of comments. Use them to discuss file and file revisions with your colleagues and clients',
  'Subscribe to a file to receive email notification when new revision is uploaded or new comment is posted. The Person who uploaded the file can edit the list of subscribers using Manage Subscriptions tool (available from Options menu)' => 'Subscribe to a file to receive email notification when new revision is uploaded or new comment is posted. The Person who uploaded the file can edit the list of subscribers using Manage Subscriptions tool (available from Options menu)',
  'Older Versions' => 'Older Versions',
  'Delete Permanently' => 'Delete Permanently',
  'Page :page' => 'Page :page',
  'Thumbnail' => 'Thumbnail',
  'File Details' => 'File Details',
  'File' => 'File',
  'Attached To' => 'Attached To',
  'Download' => 'Download',
  'There are no files in this category' => 'There are no files in this category',
  'Upload now' => 'Upload now',
  'There are no files to show' => 'There are no files to show',
  'All Files' => 'All Files',
  'All Attachments' => 'All Attachments',
  'Manage Categories' => 'Manage Categories',
  'Edit File Details' => 'Edit File Details',
  'Category' => 'Category',
  'Files' => 'Files',
  'There are no files on this page' => 'There are no files on this page',
  'Latest Version' => 'Latest Version',
  'This has no revisions' => 'This has no revisions',
  'First Version' => 'First Version',
  'New Version' => 'New Version',
  'Move To Trash' => 'Move To Trash',
  'Move To Category' => 'Move To Category',
  '&lt;None&gt;' => '&lt;None&gt;',
  'Select File' => 'Select File',
  'You are about to upload new version of <a href=":url">":name"</a> file. Older versions of this file will not be deleted but saved for future reference' => 'You are about to upload new version of <a href=":url">":name"</a> file. Older versions of this file will not be deleted but saved for future reference',
  'Notify People' => 'Notify People',
  'File <a href=":url">:name</a> has been created' => 'File <a href=":url">:name</a> has been created',
  'Set Milestone and Category' => 'Set Milestone and Category',
  'Set Category' => 'Set Category',
  'Set Visibility' => 'Set Visibility',
  'Upload Files' => 'Upload Files',
  'Description <i>(optional)</i>' => 'Description <i>(optional)</i>',
  'Add Another File' => 'Add Another File',
  '<strong>Note</strong>: Max upload size is :max_size per file' => '<strong>Note</strong>: Max upload size is :max_size per file',
  'Upload' => 'Upload',
  'File Name' => 'File Name',
  'Image preview. <a href=":url">Click to download</a> full size image' => 'Image preview. <a href=":url">Click to download</a> full size image',
  'Description for this file is not provided' => 'Description for this file is not provided',
  'Invalid file - last revision was not found' => 'Invalid file - last revision was not found',
  'Please select what you want to do with selected tickets' => 'Please select what you want to do with selected jobs',
  'Please select files that you would like to update' => 'Please select files that you would like to update',
  'File ":name" has been updated' => 'File ":name" has been updated',
  'File not uploaded' => 'File not uploaded',
  ':count attachments deleted' => ':count attachments deleted',
  ':count files moved to trash' => ':count files moved to trash',
  ':count files updated' => ':count files updated',
  'You haven\'t selected any file for upload' => 'You haven\'t selected any file for upload',
  'Adds file repository to each project. Highlights: files support versioning, can have comments, email notifications, can be organized in categories and more...' => 'Adds file repository to each client. Highlights: files support versioning, can have comments, email notifications, can be organized in categories and more...',
  'Module will be deactivated. All files created with this module will be deleted. Files attached to objects in other modules (tickets, comments etc) will not be deleted' => 'Module will be deactivated. All files created with this module will be deleted. Files attached to objects in other modules (jobs, comments etc) will not be deleted',
  'File categories' => 'File categories',
  'Exporting files data...' => 'Exporting files data...',
  '<a href=":user_url">:user_name</a> uploaded a new file' => '<a href=":user_url">:user_name</a> uploaded a new file',
  '<a href=":user_url">:user_name</a> uploaded a new file to <a href=":project_view_url">:project_name</a> project' => '<a href=":user_url">:user_name</a> uploaded a new file to <a href=":project_view_url">:project_name</a> project',
  '<a href=":user_url">:user_name</a> uploaded a new version of <a href=":url">:name</a> file' => '<a href=":user_url">:user_name</a> uploaded a new version of <a href=":url">:name</a> file',
  '<a href=":user_url">:user_name</a> uploaded a new version of <a href=":url">:name</a> file in <a href=":project_view_url">:project_name</a> project' => '<a href=":user_url">:user_name</a> uploaded a new version of <a href=":url">:name</a> file in <a href=":project_view_url">:project_name</a> project',
  'File name is required' => 'File name is required',
  'All revision moved to Trash' => 'All revision moved to Trash',
  'Upload <a href=":upload_url">more files</a> or go back to <a href=":files_url">Files</a> section' => 'Upload <a href=":upload_url">more files</a> or go back to <a href=":files_url">Files</a> section',
  'Uploading files' => 'Uploading files',
  'Done, :files_uploaded files uploaded and :files_failed uploads failed<br />' => 'Done, :files_uploaded files uploaded and :files_failed uploads failed<br />',
  'Done, :files_uploaded files uploaded<br />' => 'Done, :files_uploaded files uploaded<br />',
  'Done, :files_failed uploads failed<br />' => 'Done, :files_failed uploads failed<br />',
) ?>