<?php return array (
  'Notify People' => 'Notify People',
  'Category' => 'Category',
  'Add discussion' => 'Add discussion',
  'New Discussion' => 'New Discussion',
  'Update Discussion' => 'Update Discussion',
  'Discussions' => 'Discussions',
  'There are no discussions on this page' => 'There are no discussions on this page',
  'Discussion' => 'Discussion',
  'Replies' => 'Replies',
  'Last Reply' => 'Last Reply',
  'No discussions in this category' => 'No discussions in this category',
  'No discussions here' => 'No discussions here',
  'All Discussions' => 'All Discussions',
  'Manage Categories' => 'Manage Categories',
  'Discussion <a href=":url">:name</a> has been created' => 'Discussion <a href=":url">:name</a> has been created',
  'Set Milestone and Category' => 'Set Milestone and Category',
  'Set Category' => 'Set Category',
  'Set Visibility' => 'Set Visibility',
  'Page :page' => 'Page :page',
  'About Discussions' => 'About Discussions',
  'Just Like Online Forums' => 'Just Like Online Forums',
  'Discussions let you create a number of topics and discuss them with your team and clients. It works just like online forums - system will tell you when there are new messages in a topic and discussions with most recent comments are listed on top' => 'Discussions let you create a number of topics and discuss them with your team and clients. It works just like online forums - system will tell you when there are new messages in a topic and discussions with most recent comments are listed on top',
  'Organize in Categories and Associate with Milestones' => 'Organize in Categories and Associate with Milestones',
  'Discussions can be sorted in categories and associated with milestones; both relations are optional. Filter discussions by category using the tabs on the right' => 'Discussions can be sorted in categories and associated with milestones; both relations are optional. Filter discussions by category using the tabs on the right',
  'Attach Unlimited Number of Files' => 'Attach Unlimited Number of Files',
  'Every discussion message can have an unlimited number of attachments. System will use icons for various file types and thumbnails for images' => 'Every discussion message can have an unlimited number of attachments. System will use icons for various file types and thumbnails for images',
  'Subscribe to a discussion to receive an email notification when new message is posted. Discussion subscribers can be managed using Manage Subscriptions tool (available from Options menu)' => 'Subscribe to a discussion to receive an email notification when new message is posted. Discussion subscribers can be managed using Manage Subscriptions tool (available from Options menu)',
  'Failed to pin selected discussion' => 'Failed to pin selected discussion',
  'Failed to unpin selected discussion' => 'Failed to unpin selected discussion',
  'Discussion :discussion_name has been started' => 'Discussion :discussion_name has been started',
  'Discussion ":name" has been updated' => 'Discussion ":name" has been updated',
  'Discussion has been successfully pinned' => 'Discussion has been successfully pinned',
  'Discussion has been successfully unpinned' => 'Discussion has been successfully unpinned',
  '<strong>Pinned</strong> - This discussion is pinned' => '<strong>Pinned</strong> - This discussion is pinned',
  'Adds discussion boards to projects' => 'Adds discussion boards to projects',
  'Module will be deactivated. All discussions from all projects will be deleted' => 'Module will be deactivated. All discussions from all projects will be deleted',
  'Discussion categories' => 'Discussion categories',
  'Toggle Details' => 'Toggle Details',
  'Exporting discussions data...' => 'Exporting discussions data...',
  'Pin' => 'Pin',
  '<a href=":user_url">:user_name</a> pinned <a href=":url">:name</a> discussion' => '<a href=":user_url">:user_name</a> pinned <a href=":url">:name</a> discussion',
  '<a href=":user_url">:user_name</a> pinned <a href=":url">:name</a> discussion in <a href=":project_view_url">:project_name</a> project' => '<a href=":user_url">:user_name</a> pinned <a href=":url">:name</a> discussion in <a href=":project_view_url">:project_name</a> client',
  ':user_name pinned <a href=":object_url">:object_name</a> discussion' => ':user_name pinned <a href=":object_url">:object_name</a> discussion',
  '<a href=":user_url">:user_name</a> unpinned <a href=":url">:name</a> discussion' => '<a href=":user_url">:user_name</a> unpinned <a href=":url">:name</a> discussion',
  '<a href=":user_url">:user_name</a> unpinned <a href=":url">:name</a> discussion in <a href=":project_view_url">:project_name</a> project' => '<a href=":user_url">:user_name</a> unpinned <a href=":url">:name</a> discussion in <a href=":project_view_url">:project_name</a> client',
  ':user_name unpinned <a href=":object_url">:object_name</a> discussion' => ':user_name unpinned <a href=":object_url">:object_name</a> discussion',
  'Summary is required (min 3 letters)' => 'Summary is required (min 3 letters)',
  'Message is required (min 3 letters)' => 'Message is required (min 3 letters)',
) ?>